### ISSUE TITLE
"workers" not found

### ISSUE THREAD

**Issue by joskezelensky** [trixoniisama/auto-boost-algorithm#1]
https://github.com/trixoniisama/auto-boost-algorithm/blob/9b4ffc977312726aeeaedb68dc2f378964897ee2/auto-boost_2.0.py#L48
Isn't it better to change this to 0 instead of {WORKERS}?

**Comment by trixoniisama** [comment]
Fixed with auto-boost algorithm 2.5. The change could be backported to 2.0 though.
